name: test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

  testint:
    runs-on: ubuntu-latest
    # only run if not a fork PR targeting main repo due to permissions
    if: ${{ !(github.head_repo || github.event.pull_request.head.repo) || github.repository == (github.head_repo.full_name || github.event.pull_request.head.repo.full_name) }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm install
    - run: npm run test:integration
      env:
        GITHUB_TOKEN: ${{ secrets.INT_TEST_TOKEN != '' && secrets.INT_TEST_TOKEN || secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_HEAD_REPO: ${{ github.head_repo && github.head_repo.full_name || github.event.pull_request.head.repo.full_name || '' }}
  action-in-action:
    runs-on: ubuntu-latest
    # only run if not a fork PR targeting main repo due to permissions
    if: ${{ !(github.head_repo || github.event.pull_request.head.repo) || github.repository == (github.head_repo.full_name || github.event.pull_request.head.repo.full_name) }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm install
    - uses: ./
      id: maker
      env:
        TEST_REPOS: ${{ github.repository != 'pkgjs/meet' && github.repository || 'pkgjs/meet,pkgjs/meet' }}
        TEST_ORGS: ${{ github.repository != 'pkgjs/meet' && '' || 'pkgjs' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-04-02T17:00:00.0Z/P1D
        issueTitle: 'Test Meeting <%= date.toZonedDateTimeISO("UTC").toPlainDate().toString() %>'
        createWithin: P2D
        meetingLabels: test
        agendaLabel: meeting-agenda-test
        meetingLink: https://github.com/pkgjs/meet
        createNotes: true
        repos: ${{ env.TEST_REPOS }}
        orgs: ${{ env.TEST_ORGS }}
    - name: clean up issue
      run: node ./test/_close-issue.js ${{ secrets.GITHUB_TOKEN }} ${{ steps.maker.outputs.issueNumber }}
